export const DUMMY_POKEMON = [
  {
    id: 1,
    name: "Bulbasaur",
    type1: "grass",
    type2: "poison",
    species: "Seed Pokémon",
    height: "0.7 m",
    weight: "6.9 kg",
    abilities: "Overgrow",
    hpBase: 45,
    attackBase: 49,
    defenseBase: 49,
    spAttackBase: 65,
    spDefenseBase: 65,
    speedBase: 45,
  },
  {
    id: 2,
    name: "Ivysaur",
    type1: "grass",
    type2: "poison",
    species: "Seed Pokémon",
    height: "1.0 m",
    weight: "13.0 kg",
    abilities: "Overgrow",
    hpBase: 60,
    attackBase: 62,
    defenseBase: 63,
    spAttackBase: 80,
    spDefenseBase: 80,
    speedBase: 60,
  },
  {
    id: 3,
    name: "Venusaur",
    type1: "grass",
    type2: "poison",
    species: "Seed Pokémon",
    height: "2.0 m",
    weight: "100.0 kg",
    abilities: "Overgrow",
    hpBase: 80,
    attackBase: 82,
    defenseBase: 83,
    spAttackBase: 100,
    spDefenseBase: 100,
    speedBase: 80,
  },
  {
    id: 4,
    name: "Charmander",
    type1: "fire",
    species: "Lizard Pokémon",
    height: "0.6 m",
    weight: "8.5 kg",
    abilities: "Blaze",
    hpBase: 39,
    attackBase: 52,
    defenseBase: 43,
    spAttackBase: 60,
    spDefenseBase: 50,
    speedBase: 65,
  },
  {
    id: 5,
    name: "Charmeleon",
    type1: "fire",
    species: "Flame Pokémon",
    height: "1.1 m",
    weight: "19.0 kg",
    abilities: "Blaze",
    hpBase: 58,
    attackBase: 64,
    defenseBase: 58,
    spAttackBase: 80,
    spDefenseBase: 65,
    speedBase: 80,
  },
  {
    id: 6,
    name: "Charizard",
    type1: "fire",
    type2: "flying",
    species: "Flame Pokémon",
    height: "1.7 m",
    weight: "90.5 kg",
    abilities: "Blaze",
    hpBase: 78,
    attackBase: 84,
    defenseBase: 78,
    spAttackBase: 109,
    spDefenseBase: 85,
    speedBase: 100,
  },
  {
    id: 7,
    name: "Squirtle",
    type1: "water",
    species: "Tiny Turtle Pokémon",
    height: "0.5 m",
    weight: "9.0 kg",
    abilities: "Torrent",
    hpBase: 44,
    attackBase: 48,
    defenseBase: 65,
    spAttackBase: 50,
    spDefenseBase: 64,
    speedBase: 43,
  },
  {
    id: 8,
    name: "Wartortle",
    type1: "water",
    species: "Turtle Pokémon",
    height: "1.0 m",
    weight: "22.5 kg",
    abilities: "Torrent",
    hpBase: 59,
    attackBase: 63,
    defenseBase: 80,
    spAttackBase: 65,
    spDefenseBase: 80,
    speedBase: 58,
  },
  {
    id: 9,
    name: "Blastoise",
    type1: "water",
    species: "Shellfish Pokémon",
    height: "1.6 m",
    weight: "85.5 kg",
    abilities: "Torrent",
    hpBase: 79,
    attackBase: 83,
    defenseBase: 100,
    spAttackBase: 85,
    spDefenseBase: 105,
    speedBase: 78,
  },
  {
    id: 10,
    name: "Pikachu",
    type1: "electric",
    species: "Mouse Pokémon",
    height: "0.4 m",
    weight: "6.0 kg",
    abilities: "Static",
    hpBase: 35,
    attackBase: 55,
    defenseBase: 40,
    spAttackBase: 50,
    spDefenseBase: 50,
    speedBase: 90,
  },
  {
    id: 11,
    name: "Raichu",
    type1: "electric",
    species: "Mouse Pokémon",
    height: "0.8 m",
    weight: "30.0 kg",
    abilities: "Static",
    hpBase: 60,
    attackBase: 90,
    defenseBase: 55,
    spAttackBase: 90,
    spDefenseBase: 80,
    speedBase: 110,
  },
  {
    id: 12,
    name: "Jigglypuff",
    type1: "fairy",
    species: "Balloon Pokémon",
    height: "0.5 m",
    weight: "5.5 kg",
    abilities: "Cute Charm",
    hpBase: 115,
    attackBase: 45,
    defenseBase: 20,
    spAttackBase: 45,
    spDefenseBase: 25,
    speedBase: 20,
  },
  {
    id: 13,
    name: "Gengar",
    type1: "ghost",
    type2: "poison",
    species: "Shadow Pokémon",
    height: "1.5 m",
    weight: "40.5 kg",
    abilities: "Cursed Body",
    hpBase: 60,
    attackBase: 65,
    defenseBase: 60,
    spAttackBase: 130,
    spDefenseBase: 75,
    speedBase: 110,
  },
  {
    id: 14,
    name: "Onix",
    type1: "rock",
    type2: "ground",
    species: "Rock Snake Pokémon",
    height: "8.8 m",
    weight: "210.0 kg",
    abilities: "Rock Head",
    hpBase: 35,
    attackBase: 45,
    defenseBase: 160,
    spAttackBase: 30,
    spDefenseBase: 45,
    speedBase: 70,
  },
  {
    id: 15,
    name: "Machamp",
    type1: "fighting",
    species: "Superpower Pokémon",
    height: "1.6 m",
    weight: "130.0 kg",
    abilities: "Guts",
    hpBase: 90,
    attackBase: 130,
    defenseBase: 80,
    spAttackBase: 65,
    spDefenseBase: 85,
    speedBase: 55,
  },
    {
    id: 16,
    name: "Alakazam",
    type1: "psychic",
    species: "Psi Pokémon",
    height: "1.5 m",
    weight: "48.0 kg",
    abilities: "Synchronize",
    hpBase: 55,
    attackBase: 50,
    defenseBase: 45,
    spAttackBase: 135,
    spDefenseBase: 95,
    speedBase: 120,
  },
  {
    id: 17,
    name: "Snorlax",
    type1: "normal",
    species: "Sleeping Pokémon",
    height: "2.1 m",
    weight: "460.0 kg",
    abilities: "Thick Fat",
    hpBase: 160,
    attackBase: 110,
    defenseBase: 65,
    spAttackBase: 65,
    spDefenseBase: 110,
    speedBase: 30,
  },
  {
    id: 18,
    name: "Dragonite",
    type1: "dragon",
    type2: "flying",
    species: "Dragon Pokémon",
    height: "2.2 m",
    weight: "210.0 kg",
    abilities: "Inner Focus",
    hpBase: 91,
    attackBase: 134,
    defenseBase: 95,
    spAttackBase: 100,
    spDefenseBase: 100,
    speedBase: 80,
  },
  {
    id: 19,
    name: "Eevee",
    type1: "normal",
    species: "Evolution Pokémon",
    height: "0.3 m",
    weight: "6.5 kg",
    abilities: "Run Away",
    hpBase: 55,
    attackBase: 55,
    defenseBase: 50,
    spAttackBase: 45,
    spDefenseBase: 65,
    speedBase: 55,
  },
  {
    id: 20,
    name: "Vaporeon",
    type1: "water",
    species: "Bubble Jet Pokémon",
    height: "1.0 m",
    weight: "29.0 kg",
    abilities: "Water Absorb",
    hpBase: 130,
    attackBase: 65,
    defenseBase: 60,
    spAttackBase: 110,
    spDefenseBase: 95,
    speedBase: 65,
  },
  {
    id: 21,
    name: "Jolteon",
    type1: "electric",
    species: "Lightning Pokémon",
    height: "0.8 m",
    weight: "24.5 kg",
    abilities: "Volt Absorb",
    hpBase: 65,
    attackBase: 65,
    defenseBase: 60,
    spAttackBase: 110,
    spDefenseBase: 95,
    speedBase: 130,
  },
  {
    id: 22,
    name: "Flareon",
    type1: "fire",
    species: "Flame Pokémon",
    height: "0.9 m",
    weight: "25.0 kg",
    abilities: "Flash Fire",
    hpBase: 65,
    attackBase: 130,
    defenseBase: 60,
    spAttackBase: 95,
    spDefenseBase: 110,
    speedBase: 65,
  },
  {
    id: 23,
    name: "Lucario",
    type1: "fighting",
    type2: "steel",
    species: "Aura Pokémon",
    height: "1.2 m",
    weight: "54.0 kg",
    abilities: "Steadfast",
    hpBase: 70,
    attackBase: 110,
    defenseBase: 70,
    spAttackBase: 115,
    spDefenseBase: 70,
    speedBase: 90,
  },
  {
    id: 24,
    name: "Garchomp",
    type1: "dragon",
    type2: "ground",
    species: "Mach Pokémon",
    height: "1.9 m",
    weight: "95.0 kg",
    abilities: "Sand Veil",
    hpBase: 108,
    attackBase: 130,
    defenseBase: 95,
    spAttackBase: 80,
    spDefenseBase: 85,
    speedBase: 102,
  },
  {
    id: 25,
    name: "Tyranitar",
    type1: "rock",
    type2: "dark",
    species: "Armor Pokémon",
    height: "2.0 m",
    weight: "202.0 kg",
    abilities: "Sand Stream",
    hpBase: 100,
    attackBase: 134,
    defenseBase: 110,
    spAttackBase: 95,
    spDefenseBase: 100,
    speedBase: 61,
  },
  {
    id: 26,
    name: "Metagross",
    type1: "steel",
    type2: "psychic",
    species: "Iron Leg Pokémon",
    height: "1.6 m",
    weight: "550.0 kg",
    abilities: "Clear Body",
    hpBase: 80,
    attackBase: 135,
    defenseBase: 130,
    spAttackBase: 95,
    spDefenseBase: 90,
    speedBase: 70,
  },
  {
    id: 27,
    name: "Salamence",
    type1: "dragon",
    type2: "flying",
    species: "Dragon Pokémon",
    height: "1.5 m",
    weight: "102.6 kg",
    abilities: "Intimidate",
    hpBase: 95,
    attackBase: 135,
    defenseBase: 80,
    spAttackBase: 110,
    spDefenseBase: 80,
    speedBase: 100,
  },
  {
    id: 28,
    name: "Greninja",
    type1: "water",
    type2: "dark",
    species: "Ninja Pokémon",
    height: "1.5 m",
    weight: "40.0 kg",
    abilities: "Torrent",
    hpBase: 72,
    attackBase: 95,
    defenseBase: 67,
    spAttackBase: 103,
    spDefenseBase: 71,
    speedBase: 122,
  },
  {
    id: 29,
    name: "Aegislash",
    type1: "steel",
    type2: "ghost",
    species: "Royal Sword Pokémon",
    height: "1.7 m",
    weight: "53.0 kg",
    abilities: "Stance Change",
    hpBase: 60,
    attackBase: 50,
    defenseBase: 140,
    spAttackBase: 50,
    spDefenseBase: 140,
    speedBase: 60,
  },
  {
    id: 30,
    name: "Mewtwo",
    type1: "psychic",
    species: "Genetic Pokémon",
    height: "2.0 m",
    weight: "122.0 kg",
    abilities: "Pressure",
    hpBase: 106,
    attackBase: 110,
    defenseBase: 90,
    spAttackBase: 154,
    spDefenseBase: 90,
    speedBase: 130,
  },

  
];
